name: learn-github-actions

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Flutter Version
        id: flutter_version
        run: |
          flutter_version=$(awk '/version/{print $2}' pubspec.yaml)
          echo "::set-output name=version::$flutter_version"

      - name: Print Version
        run: echo "Flutter version is ${{ steps.flutter_version.outputs.version }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: demo_release_apk_${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
            version=$(grep -oP '^version: \K.*' pubspec.yaml)
            echo "::set-output name=version::$version"

      - name: Update pubspec.yaml
        run: |
            version=$(grep -oP '^version: \K.*' pubspec.yaml)
            new_version=${{ steps.get_version.outputs.version }}
            sed -i "s/version: $version/version: $new_version/" pubspec.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "singhanjali0502@gmail.com"
          git config --local user.name "singhanjali0502"
          git add pubspec.yaml
          git commit -m "Update version"
          git push

      - name: Get commit hash
        id: get_commit_hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
         tag_name: v1.0.0+${{ github.run_number }}
         release_name: v1.0.0+${{ github.run_number }}
         body: Release notes
         draft: false
         prerelease: false
        env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}